### ISSUE TITLE
{IF 'verb' 'value'} as opposed to ALL 'verb' 'value'/Combining filtered products

### ISSUE THREAD

**Issue by garybeans** [christianblais/Parcelify#14]
Hi Christian,

Wonderful app which makes up for the terrible shopify shipping standard options.

It is helping me solve some issues. 

I have some products which are chilled, say product name Chill A, Chill B etc.
I set up a filter to:
- exclude these from Delivery A price,
- include these to Delivery B price,

However, if a customer combines a Chill product and a Non-chill product there is no option for them. Delivery B is only available when "This rate is only valid when all the following conditions are met; all product names include......"filter"" as opposed to IF ANY of these triggers happen as opposed to ALL triggers, which is how it seems to work

I deleted the 'include' for Delivery B, but this means Delivery A+B options still shows up for customers when I don't want them to see B unless they have a chilled product.

- Perhaps there is something I have misunderstood? Or is this something which can be applied or worked around. 

Hope you can help,
Kind Regards
GB

**Comment by christianblais** [comment]
Have you tried the "At least one item must match" modifier on the filter?

**Comment by garybeans** [comment]
Hi Christian,

Thanks for replying.

I don't see where I can add that? How can I modify the filter? I only see the drop down

Field - I select 'Product Name'
Verb - Either 'Include' or 'Exclude', the others are 'Equal', 'Start with', 'End with'
Value - here I put my trigger items.

How, or where do I include something to modify it. It makes perfect sense, but I can't seem to apply what you say for the solution.

**Comment by christianblais** [comment]
Oh, it was only available for Product SKU. I just added it to Product Name as well. Sorry for the confusion. You should now see this;

<img width="439" alt="screen shot 2017-04-12 at 4 26 47 pm" src="https://cloud.githubusercontent.com/assets/596120/24977924/d7ef0c5a-1f9c-11e7-840d-d51c59f68052.png">

**Comment by garybeans** [comment]
Wow, that makes perfect sense.

Thanks again! Such a great app. Shopify should pay you a lot of money for this.
