### ISSUE TITLE
Combined shipping rates

### ISSUE THREAD

**Issue by iiTrends** [christianblais/parcelify#16]
Hi would like to set a shipping rate of $9.95 for free products and a shipping rate of $4.95 for other products. If a customer adds an item from both, I want both shipping rates to appear on the cart. Normally only any one of these shipping rate appears on the cart to be charged to the customer. I want both charges to appear. Example:

Free plus shipping product: Product A $0.00 Plus shipping $9.95
Normal product: Product B $14.99 Plus Shipping $4.95

So if customer adds Product A and Product B to cart, I want the cart to appear something similar to below;

Product A:                           $0.00
Product B:                         $14.99

Shipping:                            $9.95
Shipping:                            $4.95

Total                                  $29.89

I Hope its clear enough to understand. Can someone please help me. Will be much appreciated.

**Comment by christianblais** [comment]
The display of such information isn't possible on Shopify. They always combine rates into a single price. That being said, you can use Parcelify to create a $0 shipping rate on which you add additional charges for specific products, such as a $4.95 for SKU A and $9.95 for SKU B. But on Shopify, it will show up as a single shipping rate of $14.90.
