### ISSUE TITLE
Set up excluding Post Codes

### ISSUE THREAD

**Issue by LindaL112** [christianblais/Parcelify#17]
Hi,

Can you please point out where I'm going wrong... Here's the set up I'm trying to create:

1. Standard Mainland UK Delivery below £50 is £4
2. Free Standard Mainland UK Delivery above £50
3. Non Mainland UK Postcodes: £8

I've set up (1) and (2) filtered to GB and have no issues, however when I try to add another filter to exclude the postcodes needed for (3) it doesn't exclude them.

If I set up another rate with the postcodes for (3) and I do the 'calculate shipping' on the shopify site - it gives me the rates for both (1 or 2) and (3) - it doesn't filter out.

For example attached is the filters trying to exclude NI postcodes 
![image](https://cloud.githubusercontent.com/assets/27577035/25066234/83e1fbbc-2218-11e7-82d3-381b6ec1cd92.png)

I must be doing the filter incorrectly - can you please advise?

Thanks

**Comment by christianblais** [comment]
You'll effectively need three rates; One (1) for Mainland UK below £50, one (2) for free Mainland UK above £50, and another one (3) for non Mainland UK. Filters for 1 and 2 are identical, only the price limit changes between the two. Those two filters need to be mutually exclusive. As for the filter itself, it looks good. It can be rewritten to `^(BT)|(IM)\d{1,2}\s` (as only the BT or IM part changes), but other than that, it looks good. Trying this on my shop, it seems to work. Maybe you could share a little bit more details on what exactly doesn't work? Are you trying this in your checkout flow, as if you were a customer? The admin section of Shopify doesn't let you test with all the parameters, so I suggest you try with the checkout flow and enlighten us on exactly what doesn't work.

**Comment by LindaL112** [comment]
Hi,

Thanks I think I've resolved the issue - it was the way I was writing the postcode filters for Non Mainland UK (not shown here) that was causing the issue.
