### ISSUE TITLE
Two Categories - One Shipping Charge

### ISSUE THREAD

**Issue by 08KL8ND** [christianblais/Parcelify#18]
Hi Christian, I have a store with two categories of products that ship separately via different methods (one by weight, one by invoice price). I can configure your app to offer the correct two shipping methods as options, but is there a way to _combine_ both options into one shipping cost?

ie. if a customer buys one of each, they will be charged by weight for product 1, and by total invoice price for product 2 -- then the cart will combine _both_ shipping prices into one shipping charge. 

thank you!

**Comment by christianblais** [comment]
Unfortunately no, there's no way to do so.

**Comment by 08KL8ND** [comment]
I appreciate the response!
