### ISSUE TITLE
Price Issue

### ISSUE THREAD

**Issue by KButter** [christianblais/Parcelify#19]
Hello,

Your help is needed! We are creating 50+ custom shipping rates, so we can add specific amounts to products.  We are 99% done, but now when we put in a specific amount to add, in the check out, it changes the amount.  For example: I create a custom ship rate for an arcade game and have it add $85 for shipping with Parcelify.  When I go to our website and go through the check out on the arcade game, it puts the shipping at $170. Why is this? Can you please help in resolving this issue we are having?

Thank you,
Kristin

**Comment by KButter** [comment]
It is also pulling a different products custom shipping rate. Please see below. 
<img width="1255" alt="screen shot 2017-04-25 at 3 37 29 pm" src="https://cloud.githubusercontent.com/assets/28020903/25408953/3d9ffa20-29cd-11e7-8cc6-2de74a3c5c05.png">

**Comment by christianblais** [comment]
What happens when you buy both a Faberhouse and a Basement Barcades? I believe the prices should add up, right? If so, you don't need 50+ custom rates, you only need one, with 50+ additional charges per item.

**Comment by KButter** [comment]
Hi Christian,

Thank you for your response.  We are trying to figure out how to make Parcelify work for our website venture.  Each product is going to have a different ship cost, So we want to have product A be $30 and Product B be $100 etc. So far, when I do multiple custom prices for different products, they all show up as options.  Please see the picture below.  I have to believe it is a simple fix, but we cannot figure it out after hours of making changes.

Thank you for your assistance,
Kristin








Kristin Butterfield
GM, VP | DELTA-13 
Phone: 303-841-5697
Fax: 303-841-5222
kristin@delta-13.com					

Website: www.delta-13.com <http://www.delta-13.com/>			
Facebook <https://www.facebook.com/Delta13Billiards?ref=hl> ● Twitter <https://twitter.com/TheDelta13> ● Google + <https://plus.google.com/b/107845205416110731078/107845205416110731078/posts>		
Linkedin <https://www.linkedin.com/company/3754301?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354287958,tas:delta-13> ● YouTube <https://www.youtube.com/user/KTmoney1985> ● Pinterest <https://www.pinterest.com/thedelta13/> 



HR MGR | TAG TEAM MANUFACTURING				
10332 S. Dransfeldt Rd, Unit 103	
Parker, Colorado 80134	

Website: www.tagteammfg.com <http://www.tagteammfg.com/>
Facebook <https://www.facebook.com/pages/Tag-Team-Manufacturing/225386980992602?ref=hl> ● Google + <https://plus.google.com/b/118418606316752663419/118418606316752663419/posts> ● Linkedin <https://www.linkedin.com/company/3753523?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354500563,tas:tag+team+man>

**Comment by KButter** [comment]
Here is what our backend looks like as we have only added two custom products as we are still trying to figure out the app.

Thanks,
Kristin








Kristin Butterfield
GM, VP | DELTA-13 
Phone: 303-841-5697
Fax: 303-841-5222
kristin@delta-13.com					

Website: www.delta-13.com <http://www.delta-13.com/>			
Facebook <https://www.facebook.com/Delta13Billiards?ref=hl> ● Twitter <https://twitter.com/TheDelta13> ● Google + <https://plus.google.com/b/107845205416110731078/107845205416110731078/posts>		
Linkedin <https://www.linkedin.com/company/3754301?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354287958,tas:delta-13> ● YouTube <https://www.youtube.com/user/KTmoney1985> ● Pinterest <https://www.pinterest.com/thedelta13/> 



HR MGR | TAG TEAM MANUFACTURING				
10332 S. Dransfeldt Rd, Unit 103	
Parker, Colorado 80134	

Website: www.tagteammfg.com <http://www.tagteammfg.com/>
Facebook <https://www.facebook.com/pages/Tag-Team-Manufacturing/225386980992602?ref=hl> ● Google + <https://plus.google.com/b/118418606316752663419/118418606316752663419/posts> ● Linkedin <https://www.linkedin.com/company/3753523?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354500563,tas:tag+team+man>

**Comment by christianblais** [comment]
Have you read https://christianblais.github.io/Parcelify/#additional-cost-per-item ?

**Comment by KButter** [comment]
Yes, that is how I believe we set everything up.  Did we do something wrong?

Thanks for your assistance.

Kristin






Kristin Butterfield
GM, VP | DELTA-13 
Phone: 303-841-5697
Fax: 303-841-5222
kristin@delta-13.com					

Website: www.delta-13.com <http://www.delta-13.com/>			
Facebook <https://www.facebook.com/Delta13Billiards?ref=hl> ● Twitter <https://twitter.com/TheDelta13> ● Google + <https://plus.google.com/b/107845205416110731078/107845205416110731078/posts>		
Linkedin <https://www.linkedin.com/company/3754301?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354287958,tas:delta-13> ● YouTube <https://www.youtube.com/user/KTmoney1985> ● Pinterest <https://www.pinterest.com/thedelta13/> 



HR MGR | TAG TEAM MANUFACTURING				
10332 S. Dransfeldt Rd, Unit 103	
Parker, Colorado 80134	

Website: www.tagteammfg.com <http://www.tagteammfg.com/>
Facebook <https://www.facebook.com/pages/Tag-Team-Manufacturing/225386980992602?ref=hl> ● Google + <https://plus.google.com/b/118418606316752663419/118418606316752663419/posts> ● Linkedin <https://www.linkedin.com/company/3753523?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354500563,tas:tag+team+man>

**Comment by christianblais** [comment]
Yes. You created one rate per item instead of a single rate with multiple charges. Instead of one rate named "Basement Barcades" and another one named "Faberhouse", you want a single one, called something like "Standard Shipping", on which you'll add all your additional charges.

**Comment by KButter** [comment]
Hi Christian,

I knew it would be a simple fix we were not understanding.  I will work on this in the morning and hopefully it should work! Thank you very much for your help.

Best,
Kristin







Kristin Butterfield
GM, VP | DELTA-13 
Phone: 303-841-5697
Fax: 303-841-5222
kristin@delta-13.com					

Website: www.delta-13.com <http://www.delta-13.com/>			
Facebook <https://www.facebook.com/Delta13Billiards?ref=hl> ● Twitter <https://twitter.com/TheDelta13> ● Google + <https://plus.google.com/b/107845205416110731078/107845205416110731078/posts>		
Linkedin <https://www.linkedin.com/company/3754301?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354287958,tas:delta-13> ● YouTube <https://www.youtube.com/user/KTmoney1985> ● Pinterest <https://www.pinterest.com/thedelta13/> 



HR MGR | TAG TEAM MANUFACTURING				
10332 S. Dransfeldt Rd, Unit 103	
Parker, Colorado 80134	

Website: www.tagteammfg.com <http://www.tagteammfg.com/>
Facebook <https://www.facebook.com/pages/Tag-Team-Manufacturing/225386980992602?ref=hl> ● Google + <https://plus.google.com/b/118418606316752663419/118418606316752663419/posts> ● Linkedin <https://www.linkedin.com/company/3753523?trk=tyah&trkInfo=clickedVertical:company,idx:1-1-1,tarId:1428354500563,tas:tag+team+man>
