### ISSUE TITLE
Price in cents does not make sense.

### ISSUE THREAD

**Issue by christianblais** [christianblais/parcelify#2]
Let's accept proper integers, floats being x100 and saved as integers.

**Comment by acubest** [comment]
It really isn't too big a deal to me to type two more zeros at the end of the prices, but I'm sure it would save confusion for some users.

**Comment by christianblais** [comment]
Thanks for the feedback. Since I started accepting currencies that don't have any subcurrencies, I think it's simply best for me to leave it that way.
