### ISSUE TITLE
Multiple SKUs not working in filter field?

### ISSUE THREAD

**Issue by Kathyuk** [christianblais/Parcelify#21]
hello. 

I have created a few free shipping products in Parcelify, by making the value of the shipping zero and using the filter to select the products by creating a filter that chooses "Product SKU" "equals" then typing the sku code as the value, then clicking "At least one item must match".

It works fine for one SKU. But if I attempt to put in two codes like this: 7002 | 4759, 
or putting only one number in the filter, and creating a new filter with the second code, it stops working. When I take out the extra filter/code, it works again. Even if my logic is wrong and I shouldn't have been using the "or", I take it that creating the new filter is an "and", so neither worked for me. 

The only way I have been able to get it to work is by duplicating the rule, but having multiple free shipping methods in the checkout (when I put more than one free shipping product in the cart) is a little clumsy. Have you ever come across this problem before?
Regards, Kathy

**Comment by christianblais** [comment]
Try changing "7002 | 4759" to "7002|4759". Spaces are sensitive in regex, which means they're taken into consideration.

**Comment by Kathyuk** [comment]
That worked. Thanks.
