### ISSUE TITLE
Additional Cost Not Working - Parcelify

### ISSUE THREAD

**Issue by crystalm36** [christianblais/Parcelify#23]
Hi,
I don't understand why my additional costs are not working. 
I first set up Standard Shipping on Orders $126.00 to $200.99 and then at the bottom I added the additional charge of $20.00 rule. And it doesn't add the $20.00 when I go to check out.
I added some screenshots.

[https://cdn.shopify.com/s/files/1/1825/8649/files/parcelify.JPG?1582323482575965958](url)
[https://cdn.shopify.com/s/files/1/1825/8649/files/parcelify2.JPG?11676473400187991762](url)

Can you please please help me. I love this app

**Comment by christianblais** [comment]
Can you also share screenshots not working? Or maybe a link to your shop, so we can test it out?

**Comment by crystalm36** [comment]
Hi Christian, thanks for answering me back. I got it to work when I set it to vendor name. for some reason it wouldn't take the product name.
Love this app, it's a shame that this doesn't come standard with shopify. I think this would help solve many shipping issues for others as it did for me.
Thank you for the wonderful app!!!
Take care,
Crystal


-------- Original message --------
