### ISSUE TITLE
Hey , is there any option to create a new shipping rate based on total price ? 

### ISSUE THREAD

**Issue by AlekMarkus** [christianblais/Parcelify#24]
i have couple rates that i configured and they working wonderful. but now i need to add - if some of my customers purchase above X they will need to add extra money for the shipping 

Thanks.

**Comment by christianblais** [comment]
As replied through email, unfortunately, Parcelify, doesn't have access to customer's profile, nor their history of purchase. There's no way for me to know if a customer effectively purchased above X, except for the current purchase (for which you can use limits).
