### ISSUE TITLE
Additional cost per item not applying in checkout

### ISSUE THREAD

**Issue by mshelbo** [christianblais/Parcelify#25]
Hello, we're trying to create a shipping rule with "Additional cost per item" configuration when Vendor Name equals a value. When we save the shipping rate, it does not reflect the additional cost in the shopping cart. 

Note:  Even if we use one of the other field options (SKU or product name) or other verb options, we experience the same error.

**Comment by christianblais** [comment]
What's your store, and what are the rules you're adding?

**Comment by mshelbo** [comment]
Actually, it seems to be working now. Sorry about that! Is there possibly some kind of delay between entering configuration vs seeing the rules work in the cart?

**Comment by christianblais** [comment]
Shopify does keep a cache of shipping rates. You need to tweak your address a little bit every time to trigger an invalidation of the current cache.
