### ISSUE TITLE
Combine Parcelify flat rates with Carrier Calculated Shipping rates

### ISSUE THREAD

**Issue by cptncrnch** [christianblais/Parcelify#26]
I want to use Parcelify to just add a flat rate to specific products (Hazmat shipping fee) but still use the carrier calculated shipping rates (FedEx/UPS/USPS). The extra flat shipping fee should be added to each shipping rate or just added as another line item in the Subtotal at checkout. Is this possible to do?

**Comment by christianblais** [comment]
No, all shipping carriers are completely independent. You could build an app that acts as a proxy between Shopify and Calculated Carrier, but this isn't Parcelify's goal. Sorry.
