### ISSUE TITLE
Free Shipping 

### ISSUE THREAD

**Issue by cherryhillcoffee** [christianblais/Parcelify#29]
<img width="663" alt="screen shot 2017-09-11 at 9 27 03 am" src="https://user-images.githubusercontent.com/31862330/30291474-f09de146-96e7-11e7-9114-90cb3378f768.png">

Our free shipping stopped working this weekend...tried deleting all the discounts and start from scratch with no luck. Temporarily fixed using Shopify shipping rates but can't exclude/include products. 

Any reason why it stopped working?

**Comment by cherryhillcoffee** [comment]
Deleted it and reinstalled and now working

**Comment by christianblais** [comment]
Also for easier maintenance, instead of adding multiple filters like that, you can add a single filter and use the | operator to signify "OR", such that you could rewrite ""province exclude NT|YT|NU".
