### ISSUE TITLE
callback_url seems to return old (original) values for title and code

### ISSUE THREAD

**Issue by b3vegan** [christianblais/Parcelify#31]
Hi Christian,

First of all, awesome app! We couldn't find a paid app that does half of what this app can do. So a big thank you for putting time and effort into this app and making it open source.

SOLVED: Fulfilment company was getting old values for [title] and [code] back from API even when we had updated them in Parcelify. Turns out they were checking an old order which had been created with the old values. When they queried a new order everything was as it should be. 

Maybe this is one for the FAQ?

Q: callback_url seems to return old (original) values for [title] and [code] even though I've updated them in Parcelify.

A: Make sure you are querying for an order made with those new settings, not an old order.

**Comment by christianblais** [comment]
Thanks for the kind words and the suggestion. I'm glad you found out what was wrong.
