### ISSUE TITLE
Discount code specific shipping rates

### ISSUE THREAD

**Issue by josiahwiebe** [christianblais/Parcelify#34]
It looks like the Admin API exposes the discount code in the checkout response. Does this mean one could open up the possibility of discount code specific shipping rates?

Ruby's not my jam but I might be able to muck around with this – do you have any plans to add this type of functionality?

**Comment by christianblais** [comment]
No. This would mean an API call to Shopify on every shipping request, which wouldn't be scalable. But feel free to clone this repo and try it out by yourself, I'll be curious to know how far you can go with this.

**Comment by josiahwiebe** [comment]
Oh right, I guess right now Parcelify just creates the ship options and exposes them to the store. I'll see what I can do/what I have time for. Closing this now.
