### ISSUE TITLE
Problem with postcodes from range XX80-XX99

### ISSUE THREAD

**Issue by we00026977** [christianblais/Parcelify#36]
Hi Christian,
I am running your app on Shopify and i find out the big issue that the postcode is not working perfectly on the range postcode form XX80-X90(EX: 1080,1095). Basically, my products have two types: Yes(Bulky item), No (Bulky item) and i said Yes and No for product Vendor. There are some post codes that we can deliver the bulky item. For example:
Postcode range: 3000-4000 (bulky and non-bulky item can deliver to)
Postcode range: 4800-4900 (bulky can not but non-bulky item can deliver )
After i set all rules, 
Product Vendor = No => Free Shipping
Product Vendor = Yes, Postcode exclude 4800-49000 => Free Shipping

However, when i try to buy bulky item with the range 3080-3099. It does not say Free Shipping. Could you mind having a check with that on your code, it also happen with 1080-1099 (format XX80-XX99)?

Thank you so much. Look forward to hearing from you soon.
Best regards,
John

**Comment by christianblais** [comment]
Parcelify uses regular expressions. As described in the documentation, you need to use regular expression syntax. 3000-4000 can be expressed as [3|4][0-9]{3}, while 4800-4900 can be expressed as 48[0-9]{2}|4900.
