### ISSUE TITLE
Request: More product Filter fields?

### ISSUE THREAD

**Issue by Kalpar** [christianblais/Parcelify#37]
Is it possible to add more product based fields to the filters?

Specifically I'm looking for if a product is in a collection, and/or if it has a tag.

Other fields I think would be useful would be Product Type and Vendor.

Thanks!

**Comment by christianblais** [comment]
Unfortunately, Shopify doesn't share those information with shipping carriers. The only thing we get is SKU, name, and vendor.

**Comment by Kalpar** [comment]
According to the Carrier API (https://help.shopify.com/api/reference/carrierservice), it sends the Vendor. Could you please add that one then?

**Comment by christianblais** [comment]
Vendor is already available.

**Comment by Kalpar** [comment]
Sorry, you are correct... Missed that one.  Thanks for your help!
