### ISSUE TITLE
Upper limit on the number of rates per shop

### ISSUE THREAD

**Issue by christianblais** [christianblais/parcelify#4]
Shops should be limited to, say, 10 rates maximum to limit abuse.

**Comment by acubest** [comment]
Oh please don't do this. We have a large range of products from small items to large items weighing hundreds of pounds. We need a good number of rates to accommodate the different shipping options and carriers we need to offer our clients.

**Comment by christianblais** [comment]
What would be a good limit? Problem is, it's all running out of a single server instance, with both CPU and memory limitation. If one shop starts to abuse, we're basically screwed. After all, this is a free service, can't offer much more. 10 might have been too low though. What about... 100?

**Comment by acubest** [comment]
I think 100 is plenty for most companies. Have you thought about setting a free limit... like 100 rates. And then charging a small monthly fee for over anything over? Say $5/month for every 50 rates over? That might help with server costs. So a company using 237 rates would be paying $15/month. Something to that effect.

**Comment by christianblais** [comment]
I don't want to start charging. I think everyone's happier with a free solution. After all, the app is free, and open source. If someone needs more, they can fork the project and host on their own servers, without any limitations.

**Comment by acubest** [comment]
I totally get that. I think I was looking at it as more of a "server rental" of sorts.

**Comment by jgaull** [comment]
Thanks for building this app @christianblais! I have found it to be both the easiest to use and most flexible shipping calculator. Per your suggestion, I forked the repo and got the app up and running on my own server. Looks like it's working great.

**Comment by christianblais** [comment]
>  Per your suggestion, I forked the repo and got the app up and running on my own server. Looks like it's working great.

I think you're the first one doing so! Thanks so much for getting back to me. If you have anything to suggest to make this process easier, please let me know.

**Comment by jgaull** [comment]
It would be excellent to have the URLs that go into the app settings in Shopify. It took me some time to figure out the redirection URL.

It would also be helpful to have a list of the environment vars somewhere. I had to search through the source code to find them.

Thanks again!!

**Comment by onedanshow** [comment]
@christianblais  Also a 👍 for writing this app!  Powerful, and open source!

**Comment by onedanshow** [comment]
@jgaull Did you run into this issue https://github.com/christianblais/parcelify/issues/5 while setting up?

**Comment by jgaull** [comment]
@onedanshow Not that I recall, but I see that you've figured out the issue. Glad to hear it!
