### ISSUE TITLE
Repeatedly shows error page

### ISSUE THREAD

**Issue by oliviu-rockstar** [christianblais/parcelify#5]
Hi Christian.

I am trying to customize your app and I'm getting redirected to error.html.erb repeatedly.
It says I need to purchase Advanced Shopify plan on the store but that's what I did a few weeks ago.

I deployed your app on my heroku account and installed it on my store(advanced plan).
Please let me know if anything needs to be configured for your app use.

Thanks,
Oliviu

**Comment by onedanshow** [comment]
@oliviu-rockstar  I'm in the same boat, and I'm on a Shopify Plus store.  Deployed to Heroku, ran migrations, created the app under a Shopify Partner account.  

Did you ever find out what the issue was?

**Comment by onedanshow** [comment]
@oliviu-rockstar  Make sure you setup environment variables for `APPLICATION_URL`, `SHOPIFY_CLIENT_API_KEY`, and `SHOPIFY_CLIENT_API_SECRET`.  Then the app will work just fine.

**Comment by christianblais** [comment]
If you want to submit a pull request to update the readme file with that information, I'll gladly merge it in.
